name: genDiff-check
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - run: make test
      env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: make test-coverage
          coverageLocations: ${{github.workplace}}/build/logs/clover.xml:clover
          debug: true